FROM python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /server
COPY ./backend/requirements.txt /server/
RUN pip3 install -r requirements.txt
COPY ./backend/ /server/
COPY ./wait-for-it.sh /server/
COPY ./backend.sh /server/
RUN apt-get -q update && apt-get -qy install netcat
RUN chmod +x wait-for-it.sh
RUN chmod +x backend.sh